# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('server', models.CharField(max_length=20, verbose_name='redis\u540d')),
                ('db', models.CharField(max_length=20, verbose_name='db\u540d')),
                ('key', models.CharField(db_index=True, max_length=120, verbose_name='key')),
                ('old_value', models.TextField(verbose_name='old value')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('type', models.CharField(max_length=10, verbose_name='\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u64cd\u4f5c\u8bb0\u5f55',
                'verbose_name_plural': '\u64cd\u4f5c\u8bb0\u5f55',
            },
        ),
    ]
