# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisconf',
            name='socket',
            field=models.CharField(default='', max_length=64, verbose_name='socket'),
        ),
    ]
